#.travis.yml

language: node_js
node_js:
  - "8.1.2"

branches:
  only:
    - master

before_script:
  - "echo \"export default {  firebase: {    apiKey: '${FIREBASE_API_KEY}',    authDomain: '${FIREBASE_AUTH_DOMAIN}',    databaseURL: '${FIREBASE_DATABASE_URL}',    projectId: '${FIREBASE_PROJECT_ID}',    storageBucket: '${FIREBASE_STORAGE_BUCKET}',    messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}'  }}\" > src/app/Configs/index.ts"
  - "cat src/app/Configs/index.ts"
  - npm i npm@4 -g
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - cd functions
  - npm install
  - cd ..

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

#notifications:
#  email:
#    on_failure: change
#    on_success: change
