#.travis.yml

language: node_js
node_js:
  - "8.1.2"

branches:
  only:
    - master

before_script:
  - npm i npm@4 -g
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - cd functions
  - npm install
  - cd ..
  - 'echo "export default {" >> src/app/Configs/index.ts'
  - 'echo "  firebase: {" >> src/app/Configs/index.ts'
  - 'echo "    \"apiKey\": \"${FIREBASE_API_KEY}\"," >> src/app/Configs/index.ts'
  - 'echo "    \"authDomain\": \"${FIREBASE_AUTH_DOMAIN}\"," >> src/app/Configs/index.ts'
  - 'echo "    \"databaseURL\": \"${FIREBASE_DATABASE_URL}\"," >> src/app/Configs/index.ts'
  - 'echo "    \"projectId\": \"${FIREBASE_PROJECT_ID}\"," >> src/app/Configs/index.ts'
  - 'echo "    \"storageBucket\": \"${FIREBASE_STORAGE_BUCKET}\"," >> src/app/Configs/index.ts'
  - 'echo "    \"messagingSenderId\": \"${FIREBASE_MESSAGING_SENDER_ID}\"" >> src/app/Configs/index.ts'
  - 'echo "    }" >> src/app/Configs/index.ts'
  - 'echo "  }" >> src/app/Configs/index.ts'


script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

#notifications:
#  email:
#    on_failure: change
#    on_success: change
